name: Deploy to Firebase Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: 'functions/yarn.lock'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile
        working-directory: ./functions

      - name: Build TypeScript
        run: yarn build
        working-directory: ./functions

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Deploy to Google Cloud'
        run: ./deploy.sh
